### PR TITLE
added tvOS support, rolled back macOS required version

### PR DESCRIPTION
**Pull request by ecompton3**

### CODE REVIEW

**Comment by kconner** [comment]
@ecompton3 1. Please review the commits I added; 2. What's the idea behind Carthage/Build/*?

**Comment by ecompton3** [comment]
That would be just a mistake on my part with my commit, I'll remove that!

**Comment by ecompton3** [comment]
@kconner removed it and added a line to .gitignore to prevent that from happening again

**Comment by kconner** [comment]
@ecompton3 Cool; I'm gonna squash that into your first commit so the history doesn't keep the build files.

**Pull request merged**
